export interface DevSkipStage {
  id: number;
  slug: string;
  name: string;
  subtitle: string;
  route: string;
  actionButtonLabel: string;
  nextStageId?: number;
  prevStageId?: number;
  category: 'auth' | 'onboarding' | 'dashboard' | 'tracker' | 'tools' | 'adaptive' | 'analytics';
  description: string;
  uiHighlights: string[];
  mockState: {
    dashboardState: 'empty' | 'breakfast' | 'midday' | 'complete' | 'overbudget' | 'checkin_ready';
    trackerState: 'empty' | 'breakfast' | 'midday' | 'complete' | 'overbudget';
    analyticsState: 'empty' | 'populated_deficit' | 'populated_bulk';
    savedMealsState: 'empty' | 'populated';
    hasPendingWeight: boolean;
    hasPendingCheckIn: boolean;
    onboardingStep?: number;
    showOnboarding?: boolean;
    isLoggedIn?: boolean;
  };
}

export const DEV_SKIP_STAGES: DevSkipStage[] = [
  {
    id: 1,
    slug: 'login',
    name: '1. Welcome & Login',
    subtitle: 'Unauthenticated entry point & guest mode',
    route: '/login',
    actionButtonLabel: 'Start Onboarding',
    nextStageId: 2,
    category: 'auth',
    description: 'First landing experience with brand branding, Google login, and Guest mode exploration.',
    uiHighlights: ['Google / Email login forms', 'Guest session CTA', 'GramGains branding'],
    mockState: {
      dashboardState: 'empty',
      trackerState: 'empty',
      analyticsState: 'empty',
      savedMealsState: 'empty',
      hasPendingWeight: false,
      hasPendingCheckIn: false,
      isLoggedIn: false,
    },
  },
  {
    id: 2,
    slug: 'onboarding',
    name: '2. Onboarding Wizard',
    subtitle: '4-Step metabolic calibration wizard',
    route: '/?onboarding=true',
    actionButtonLabel: 'Finish Onboarding',
    prevStageId: 1,
    nextStageId: 3,
    category: 'onboarding',
    description: 'Interactive wizard calculating BMR, TDEE, and macro split based on personal metrics.',
    uiHighlights: ['Step 1: Bio info', 'Step 2: Weight & Activity', 'Step 3: Goals', 'Step 4: Target Review'],
    mockState: {
      dashboardState: 'empty',
      trackerState: 'empty',
      analyticsState: 'empty',
      savedMealsState: 'empty',
      hasPendingWeight: false,
      hasPendingCheckIn: false,
      showOnboarding: true,
      onboardingStep: 1,
      isLoggedIn: true,
    },
  },
  {
    id: 3,
    slug: 'dashboard-empty',
    name: '3. Day 1 Zero State',
    subtitle: 'Fresh dashboard, 0 kcal, weigh-in banner',
    route: '/',
    actionButtonLabel: 'Record Morning Weight',
    prevStageId: 2,
    nextStageId: 4,
    category: 'dashboard',
    description: 'First impression after completing onboarding. Clean zero-state rings and morning weight prompt.',
    uiHighlights: ['Zero calorie donut ring', 'Empty meal timeline', 'Morning weigh-in banner prompt'],
    mockState: {
      dashboardState: 'empty',
      trackerState: 'empty',
      analyticsState: 'empty',
      savedMealsState: 'empty',
      hasPendingWeight: true,
      hasPendingCheckIn: false,
      isLoggedIn: true,
    },
  },
  {
    id: 4,
    slug: 'weight-modal',
    name: '4. Morning Weigh-In',
    subtitle: 'Daily weight modal calibration',
    route: '/',
    actionButtonLabel: 'Open Food Tracker',
    prevStageId: 3,
    nextStageId: 5,
    category: 'dashboard',
    description: 'User enters their morning scale weight (78.5 kg) to begin calibrating the adaptive engine.',
    uiHighlights: ['DailyWeightModal popup', 'Weight delta tracking', 'Instant banner dismissal'],
    mockState: {
      dashboardState: 'empty',
      trackerState: 'empty',
      analyticsState: 'empty',
      savedMealsState: 'empty',
      hasPendingWeight: false,
      hasPendingCheckIn: false,
      isLoggedIn: true,
    },
  },
  {
    id: 5,
    slug: 'tracker-empty',
    name: '5. Daily Tracker (Empty)',
    subtitle: 'Blank meal slots ready for logging',
    route: '/tracker',
    actionButtonLabel: 'Log Breakfast',
    prevStageId: 4,
    nextStageId: 6,
    category: 'tracker',
    description: 'Interactive meal cards for Breakfast, Lunch, Dinner, Snacks with IFCT/INDB search actions.',
    uiHighlights: ['4 Meal slot cards', 'Zero water tracker', 'Quick search & custom food entry'],
    mockState: {
      dashboardState: 'empty',
      trackerState: 'empty',
      analyticsState: 'empty',
      savedMealsState: 'empty',
      hasPendingWeight: false,
      hasPendingCheckIn: false,
      isLoggedIn: true,
    },
  },
  {
    id: 6,
    slug: 'tracker-midday',
    name: '6. Midday Partial Progress',
    subtitle: 'Breakfast & Lunch logged, 1,180 kcal',
    route: '/tracker',
    actionButtonLabel: 'Complete Day Meals',
    prevStageId: 5,
    nextStageId: 7,
    category: 'tracker',
    description: 'Midday realistic state showing Breakfast (Oats & Eggs) and Lunch (Grilled Chicken Bowl) with 1,500ml water.',
    uiHighlights: ['Partial macro completion (52%)', 'Water progress at 50%', 'Expanded meal cards'],
    mockState: {
      dashboardState: 'midday',
      trackerState: 'midday',
      analyticsState: 'empty',
      savedMealsState: 'empty',
      hasPendingWeight: false,
      hasPendingCheckIn: false,
      isLoggedIn: true,
    },
  },
  {
    id: 7,
    slug: 'dashboard-complete',
    name: '7. Daily Goals Met',
    subtitle: 'Target reached: 2,160 kcal, 100% protein',
    route: '/',
    actionButtonLabel: 'View Saved Meals',
    prevStageId: 6,
    nextStageId: 8,
    category: 'dashboard',
    description: 'End-of-day triumphant state. All macros within 2% of target, protein goal met, 3L water logged.',
    uiHighlights: ['Green completed calorie ring', '100% Protein badge', 'Full 4-meal timeline', 'Full 3L water'],
    mockState: {
      dashboardState: 'complete',
      trackerState: 'complete',
      analyticsState: 'empty',
      savedMealsState: 'empty',
      hasPendingWeight: false,
      hasPendingCheckIn: false,
      isLoggedIn: true,
    },
  },
  {
    id: 8,
    slug: 'saved-meals',
    name: '8. Saved Meal Templates',
    subtitle: 'Template library & 1-click meal re-use',
    route: '/saved-meals',
    actionButtonLabel: 'Open Calculator',
    prevStageId: 7,
    nextStageId: 9,
    category: 'tools',
    description: 'Curated high-protein meal templates (Power Oatmeal, High-Protein Chicken Bowl, Night Casein Shake).',
    uiHighlights: ['Saved meal cards with macros', '1-Click "Log to Today"', 'Empty state illustration toggle'],
    mockState: {
      dashboardState: 'complete',
      trackerState: 'complete',
      analyticsState: 'empty',
      savedMealsState: 'populated',
      hasPendingWeight: false,
      hasPendingCheckIn: false,
      isLoggedIn: true,
    },
  },
  {
    id: 9,
    slug: 'calculator',
    name: '9. Macro & TDEE Calculator',
    subtitle: 'Mifflin-St Jeor metabolic calculator',
    route: '/calculator',
    actionButtonLabel: 'Simulate Adaptive Check-In',
    prevStageId: 8,
    nextStageId: 10,
    category: 'tools',
    description: 'Interactive calculator for testing calorie deficits, maintenance, and surpluses with macro splits.',
    uiHighlights: ['Slider adjustments', 'Deficit/Surplus comparison', 'Recommended macro splits'],
    mockState: {
      dashboardState: 'complete',
      trackerState: 'complete',
      analyticsState: 'empty',
      savedMealsState: 'populated',
      hasPendingWeight: false,
      hasPendingCheckIn: false,
      isLoggedIn: true,
    },
  },
  {
    id: 10,
    slug: 'adaptive-checkin',
    name: '10. Weekly Adaptive Check-In',
    subtitle: 'AI metabolic engine +125 kcal adjustment',
    route: '/',
    actionButtonLabel: 'View Analytics Trends',
    prevStageId: 9,
    nextStageId: 11,
    category: 'adaptive',
    description: 'Weekly calibration banner alerts user that metabolic adaptation was detected, with interactive modal review.',
    uiHighlights: ['WeeklyCheckInBanner prompt', 'WeeklyCheckInModal comparison', 'Apply adjustment action'],
    mockState: {
      dashboardState: 'checkin_ready',
      trackerState: 'complete',
      analyticsState: 'populated_deficit',
      savedMealsState: 'populated',
      hasPendingWeight: false,
      hasPendingCheckIn: true,
      isLoggedIn: true,
    },
  },
  {
    id: 11,
    slug: 'analytics-30d',
    name: '11. 30-Day Trend Analytics',
    subtitle: 'True TDEE, weight slope & adherence',
    route: '/analytics',
    actionButtonLabel: 'Open Profile Settings',
    prevStageId: 10,
    nextStageId: 12,
    category: 'analytics',
    description: 'Full 30-day analytics dashboard with rolling weight trendline, expenditure graph, and chrononutrition timing.',
    uiHighlights: ['WeightTrendChart with 7d MA', 'MetabolicEngineCard (True TDEE)', 'Adherence & Chrono timing'],
    mockState: {
      dashboardState: 'complete',
      trackerState: 'complete',
      analyticsState: 'populated_deficit',
      savedMealsState: 'populated',
      hasPendingWeight: false,
      hasPendingCheckIn: false,
      isLoggedIn: true,
    },
  },
  {
    id: 12,
    slug: 'profile',
    name: '12. Profile & Goal Settings',
    subtitle: 'Target overrides & check-in day',
    route: '/profile',
    actionButtonLabel: 'Restart Tour (Stage 1)',
    prevStageId: 11,
    nextStageId: 1,
    category: 'tools',
    description: 'Configuration for user targets, macro distribution presets, weekly check-in day, and account settings.',
    uiHighlights: ['Calorie target override', 'Macro ratio selector', 'Check-in day of week preference'],
    mockState: {
      dashboardState: 'complete',
      trackerState: 'complete',
      analyticsState: 'populated_deficit',
      savedMealsState: 'populated',
      hasPendingWeight: false,
      hasPendingCheckIn: false,
      isLoggedIn: true,
    },
  },
];

// Rich scenario builders for each domain
export const SCENARIO_DATA = {
  // --- DASHBOARD SCENARIOS ---
  dashboard: {
    empty: {
      summary: {
        date: new Date().toISOString().split('T')[0],
        calories: { target: 2000, consumed: 0, remaining: 2000, percentageDone: 0 },
        macros: {
          protein: { consumed: 0, target: 160, unit: 'g' },
          carbohydrates: { consumed: 0, target: 200, unit: 'g' },
          fat: { consumed: 0, target: 60, unit: 'g' },
          fiber: { consumed: 0, target: 30, unit: 'g' },
        },
        water: { consumed: 0, target: 3000, unit: 'ml', percentageDone: 0 },
        totalMealsLogged: 0,
      },
      heatmap: {
        daysCount: 90,
        targetCalories: 2000,
        accountCreatedAt: new Date().toISOString(),
        heatmap: [],
      },
    },
    breakfast: {
      summary: {
        date: new Date().toISOString().split('T')[0],
        calories: { target: 2000, consumed: 460, remaining: 1540, percentageDone: 23 },
        macros: {
          protein: { consumed: 35, target: 160, unit: 'g' },
          carbohydrates: { consumed: 52, target: 200, unit: 'g' },
          fat: { consumed: 12, target: 60, unit: 'g' },
          fiber: { consumed: 9, target: 30, unit: 'g' },
        },
        water: { consumed: 750, target: 3000, unit: 'ml', percentageDone: 25 },
        totalMealsLogged: 1,
      },
      heatmap: {
        daysCount: 90,
        targetCalories: 2000,
        accountCreatedAt: '2026-09-01T00:00:00.000Z',
        heatmap: [{ date: new Date().toISOString().split('T')[0], count: 1, totalCalories: 460, level: 1 }],
      },
    },
    midday: {
      summary: {
        date: new Date().toISOString().split('T')[0],
        calories: { target: 2000, consumed: 1180, remaining: 820, percentageDone: 59 },
        macros: {
          protein: { consumed: 85, target: 160, unit: 'g' },
          carbohydrates: { consumed: 125, target: 200, unit: 'g' },
          fat: { consumed: 36, target: 60, unit: 'g' },
          fiber: { consumed: 16, target: 30, unit: 'g' },
        },
        water: { consumed: 1750, target: 3000, unit: 'ml', percentageDone: 58 },
        totalMealsLogged: 2,
      },
      heatmap: {
        daysCount: 90,
        targetCalories: 2000,
        accountCreatedAt: '2026-09-01T00:00:00.000Z',
        heatmap: [{ date: new Date().toISOString().split('T')[0], count: 2, totalCalories: 1180, level: 2 }],
      },
    },
    complete: {
      summary: {
        date: new Date().toISOString().split('T')[0],
        calories: { target: 2000, consumed: 1980, remaining: 20, percentageDone: 99 },
        macros: {
          protein: { consumed: 164, target: 160, unit: 'g' },
          carbohydrates: { consumed: 195, target: 200, unit: 'g' },
          fat: { consumed: 58, target: 60, unit: 'g' },
          fiber: { consumed: 31, target: 30, unit: 'g' },
        },
        water: { consumed: 3000, target: 3000, unit: 'ml', percentageDone: 100 },
        totalMealsLogged: 4,
      },
      heatmap: {
        daysCount: 90,
        targetCalories: 2000,
        accountCreatedAt: '2026-08-01T00:00:00.000Z',
        heatmap: [
          { date: new Date().toISOString().split('T')[0], count: 4, totalCalories: 1980, level: 4 },
          { date: '2026-10-01', count: 3, totalCalories: 1920, level: 4 },
          { date: '2026-09-30', count: 4, totalCalories: 2010, level: 4 },
          { date: '2026-09-29', count: 3, totalCalories: 1890, level: 3 },
        ],
      },
    },
    overbudget: {
      summary: {
        date: new Date().toISOString().split('T')[0],
        calories: { target: 2000, consumed: 2550, remaining: -550, percentageDone: 128 },
        macros: {
          protein: { consumed: 175, target: 160, unit: 'g' },
          carbohydrates: { consumed: 285, target: 200, unit: 'g' },
          fat: { consumed: 88, target: 60, unit: 'g' },
          fiber: { consumed: 24, target: 30, unit: 'g' },
        },
        water: { consumed: 2500, target: 3000, unit: 'ml', percentageDone: 83 },
        totalMealsLogged: 5,
      },
      heatmap: {
        daysCount: 90,
        targetCalories: 2000,
        accountCreatedAt: '2026-08-01T00:00:00.000Z',
        heatmap: [{ date: new Date().toISOString().split('T')[0], count: 5, totalCalories: 2550, level: 4 }],
      },
    },
  },

  // --- DAILY TRACKER LOGS ---
  tracker: {
    empty: {
      date: new Date().toISOString().split('T')[0],
      summary: { calories: 0, protein: 0, carbohydrates: 0, fat: 0, fiber: 0 },
      logs: [],
    },
    breakfast: {
      date: new Date().toISOString().split('T')[0],
      summary: { calories: 460, protein: 35, carbohydrates: 52, fat: 12, fiber: 9 },
      logs: [
        {
          id: 'dev-log-b1',
          date: new Date().toISOString().split('T')[0],
          mealType: 'BREAKFAST',
          foodId: 'food-oats',
          food: {
            id: 'food-oats',
            name: 'Rolled Oats with Whey',
            aliases: ['oats', 'oatmeal'],
            category: 'Cereals',
            servingUnit: 'g',
            servingWeight: 60,
            calories: 320,
            protein: 26,
            carbohydrates: 44,
            fat: 4.5,
            fiber: 7,
            source: 'IFCT',
            layer: 1,
          },
          servings: 1,
          weightGrams: 60,
          unitLabel: 'g',
          calories: 320,
          protein: 26,
          carbohydrates: 44,
          fat: 4.5,
          fiber: 7,
          createdAt: new Date().toISOString(),
        },
        {
          id: 'dev-log-b2',
          date: new Date().toISOString().split('T')[0],
          mealType: 'BREAKFAST',
          foodId: 'food-eggs',
          food: {
            id: 'food-eggs',
            name: 'Boiled Egg Whites (3 large)',
            aliases: ['egg whites'],
            category: 'Poultry',
            servingUnit: 'item',
            servingWeight: 100,
            calories: 140,
            protein: 9,
            carbohydrates: 8,
            fat: 7.5,
            fiber: 2,
            source: 'INDB',
            layer: 1,
          },
          servings: 1,
          weightGrams: 100,
          unitLabel: 'item',
          calories: 140,
          protein: 9,
          carbohydrates: 8,
          fat: 7.5,
          fiber: 2,
          createdAt: new Date().toISOString(),
        },
      ],
    },
    midday: {
      date: new Date().toISOString().split('T')[0],
      summary: { calories: 1180, protein: 85, carbohydrates: 125, fat: 36, fiber: 16 },
      logs: [
        {
          id: 'dev-log-b1',
          date: new Date().toISOString().split('T')[0],
          mealType: 'BREAKFAST',
          foodId: 'food-oats',
          food: {
            id: 'food-oats',
            name: 'Rolled Oats with Whey',
            category: 'Cereals',
            servingUnit: 'g',
            servingWeight: 60,
            calories: 320,
            protein: 26,
            carbohydrates: 44,
            fat: 4.5,
            fiber: 7,
            source: 'IFCT',
            layer: 1,
          },
          servings: 1,
          weightGrams: 60,
          unitLabel: 'g',
          calories: 320,
          protein: 26,
          carbohydrates: 44,
          fat: 4.5,
          fiber: 7,
          createdAt: new Date().toISOString(),
        },
        {
          id: 'dev-log-l1',
          date: new Date().toISOString().split('T')[0],
          mealType: 'LUNCH',
          foodId: 'food-chicken-rice',
          food: {
            id: 'food-chicken-rice',
            name: 'Grilled Herb Chicken with Jasmine Rice',
            category: 'Poultry',
            servingUnit: 'plate',
            servingWeight: 350,
            calories: 720,
            protein: 50,
            carbohydrates: 73,
            fat: 24,
            fiber: 7,
            source: 'INDB',
            layer: 1,
          },
          servings: 1,
          weightGrams: 350,
          unitLabel: 'plate',
          calories: 720,
          protein: 50,
          carbohydrates: 73,
          fat: 24,
          fiber: 7,
          createdAt: new Date().toISOString(),
        },
        {
          id: 'dev-log-s1',
          date: new Date().toISOString().split('T')[0],
          mealType: 'SNACK',
          foodId: 'food-apple',
          food: {
            id: 'food-apple',
            name: 'Crisp Apple & Almond Butter',
            category: 'Fruits',
            servingUnit: 'portion',
            servingWeight: 150,
            calories: 140,
            protein: 9,
            carbohydrates: 8,
            fat: 7.5,
            fiber: 2,
            source: 'IFCT',
            layer: 1,
          },
          servings: 1,
          weightGrams: 150,
          unitLabel: 'portion',
          calories: 140,
          protein: 9,
          carbohydrates: 8,
          fat: 7.5,
          fiber: 2,
          createdAt: new Date().toISOString(),
        },
      ],
    },
    complete: {
      date: new Date().toISOString().split('T')[0],
      summary: { calories: 1980, protein: 164, carbohydrates: 195, fat: 58, fiber: 31 },
      logs: [
        {
          id: 'dev-log-b1',
          date: new Date().toISOString().split('T')[0],
          mealType: 'BREAKFAST',
          foodId: 'food-oats',
          food: {
            id: 'food-oats',
            name: 'Rolled Oats with Whey',
            category: 'Cereals',
            servingUnit: 'g',
            servingWeight: 60,
            calories: 320,
            protein: 26,
            carbohydrates: 44,
            fat: 4.5,
            fiber: 7,
            source: 'IFCT',
            layer: 1,
          },
          servings: 1,
          weightGrams: 60,
          unitLabel: 'g',
          calories: 320,
          protein: 26,
          carbohydrates: 44,
          fat: 4.5,
          fiber: 7,
          createdAt: new Date().toISOString(),
        },
        {
          id: 'dev-log-l1',
          date: new Date().toISOString().split('T')[0],
          mealType: 'LUNCH',
          foodId: 'food-chicken-rice',
          food: {
            id: 'food-chicken-rice',
            name: 'Grilled Herb Chicken with Jasmine Rice',
            category: 'Poultry',
            servingUnit: 'plate',
            servingWeight: 350,
            calories: 720,
            protein: 50,
            carbohydrates: 73,
            fat: 24,
            fiber: 7,
            source: 'INDB',
            layer: 1,
          },
          servings: 1,
          weightGrams: 350,
          unitLabel: 'plate',
          calories: 720,
          protein: 50,
          carbohydrates: 73,
          fat: 24,
          fiber: 7,
          createdAt: new Date().toISOString(),
        },
        {
          id: 'dev-log-d1',
          date: new Date().toISOString().split('T')[0],
          mealType: 'DINNER',
          foodId: 'food-salmon-quinoa',
          food: {
            id: 'food-salmon-quinoa',
            name: 'Pan-Seared Salmon with Steamed Quinoa & Asparagus',
            category: 'Fish',
            servingUnit: 'fillet',
            servingWeight: 320,
            calories: 680,
            protein: 56,
            carbohydrates: 54,
            fat: 22,
            fiber: 12,
            source: 'INDB',
            layer: 1,
          },
          servings: 1,
          weightGrams: 320,
          unitLabel: 'fillet',
          calories: 680,
          protein: 56,
          carbohydrates: 54,
          fat: 22,
          fiber: 12,
          createdAt: new Date().toISOString(),
        },
        {
          id: 'dev-log-s2',
          date: new Date().toISOString().split('T')[0],
          mealType: 'SNACK',
          foodId: 'food-casein-berries',
          food: {
            id: 'food-casein-berries',
            name: 'Night Casein Pudding with Blueberries',
            category: 'Dairy',
            servingUnit: 'bowl',
            servingWeight: 200,
            calories: 260,
            protein: 32,
            carbohydrates: 24,
            fat: 7,
            fiber: 5,
            source: 'IFCT',
            layer: 1,
          },
          servings: 1,
          weightGrams: 200,
          unitLabel: 'bowl',
          calories: 260,
          protein: 32,
          carbohydrates: 24,
          fat: 7,
          fiber: 5,
          createdAt: new Date().toISOString(),
        },
      ],
    },
  },

  // --- SAVED MEALS ---
  savedMeals: {
    empty: [],
    populated: [
      {
        id: 'saved-001',
        name: 'High-Protein Muscle Oatmeal',
        description: 'Rolled oats with 1 scoop vanilla whey, chia seeds, and banana',
        items: [
          { foodId: 'food-oats', weightGrams: 60 },
          { foodId: 'food-whey', weightGrams: 30 },
          { foodId: 'food-banana', weightGrams: 100 },
        ],
        totalCalories: 480,
        totalProtein: 38,
        totalCarbs: 65,
        totalFat: 8,
        totalFiber: 9,
      },
      {
        id: 'saved-002',
        name: 'Grilled Herb Chicken Bowl',
        description: 'Tender chicken breast, turmeric basmati rice, roasted broccoli',
        items: [
          { foodId: 'food-chicken', weightGrams: 180 },
          { foodId: 'food-rice', weightGrams: 150 },
          { foodId: 'food-broccoli', weightGrams: 100 },
        ],
        totalCalories: 640,
        totalProtein: 52,
        totalCarbs: 72,
        totalFat: 14,
        totalFiber: 7,
      },
      {
        id: 'saved-003',
        name: 'Bedtime Casein Mousse',
        description: 'Slow-digesting micellar casein with almond butter & strawberries',
        items: [
          { foodId: 'food-casein', weightGrams: 35 },
          { foodId: 'food-almond-butter', weightGrams: 15 },
          { foodId: 'food-strawberries', weightGrams: 80 },
        ],
        totalCalories: 290,
        totalProtein: 30,
        totalCarbs: 18,
        totalFat: 9,
        totalFiber: 4,
      },
    ],
  },

  // --- ADAPTIVE METABOLIC CHECK-IN ---
  adaptive: {
    status: {
      isAdaptiveEnabled: true,
      confidence: {
        level: 'HIGH',
        score: 88,
        validFoodDays: 24,
        validWeightDays: 26,
        evaluationWindowDays: 30,
        message: 'High confidence based on 26 daily weigh-ins and 24 full nutrition logs.',
      },
      expenditure: {
        formulaBaselineTdee: 2350,
        observedTdee: 2475,
        effectiveTdee: 2475,
        dailyEnergySurplusKcal: -125,
        unit: 'kcal/day',
      },
      weightTrend: {
        latestRawKg: 78.4,
        latestTrendKg: 78.1,
        velocityKgPerDay: -0.065,
        velocityKgPerWeek: -0.455,
        targetVelocityKgPerWeek: -0.5,
      },
      targets: {
        currentCalories: 2000,
        recommendedCalories: 2080,
        adjustmentKcal: +80,
        isBelowSafetyFloor: false,
        safetyFloorKcal: 1500,
        isAggressiveRate: false,
        recommendedMacros: {
          proteinGrams: 165,
          carbsGrams: 205,
          fatGrams: 64,
          fiberGrams: 30,
          macroRatios: { protein: 32, carbs: 40, fat: 28 },
        },
      },
    },
    checkIn: {
      id: 'checkin-dev-001',
      date: new Date().toISOString().split('T')[0],
      currentCalories: 2000,
      recommendedCalories: 2080,
      adjustmentKcal: +80,
      confidenceLevel: 'HIGH',
      analysisReason: 'Your actual expenditure (2,475 kcal) is higher than formula predictions. We recommend a +80 kcal bump to preserve muscle mass.',
      recommendedMacros: {
        proteinGrams: 165,
        carbsGrams: 205,
        fatGrams: 64,
        fiberGrams: 30,
      },
    },
  },

  // --- ANALYTICS OVERVIEWS & TRENDS ---
  analytics: {
    empty: {
      overview: {
        daysLogged: 2,
        averageCalories: 1100,
        targetCalories: 2000,
        adherenceScore: 35,
        averageProteinGrams: 55,
        weightChangeKg: 0,
        message: 'Log for at least 7 days to unlock metabolic rate trends and chrononutrition analytics.',
      },
      trends: {
        dailyPoints: [],
        movingAverageTrend: [],
      },
      patterns: {
        timingDistribution: [],
        weekdayVsWeekend: { weekdayAvg: 0, weekendAvg: 0 },
      },
    },
    populated: {
      overview: {
        daysLogged: 28,
        averageCalories: 1980,
        targetCalories: 2000,
        adherenceScore: 92,
        averageProteinGrams: 162,
        weightChangeKg: -2.3,
        startWeightKg: 80.7,
        currentWeightKg: 78.4,
        message: 'Outstanding adherence over the past 30 days! Metabolic adaptation rate is stable.',
      },
      trends: {
        dailyPoints: Array.from({ length: 30 }).map((_, i) => {
          const d = new Date();
          d.setDate(d.getDate() - (29 - i));
          const dateStr = d.toISOString().split('T')[0];
          const rawWeight = 80.7 - (i * 0.08) + ((i % 3 === 0 ? 0.2 : -0.15));
          const trendWeight = 80.7 - (i * 0.078);
          return {
            date: dateStr,
            caloriesConsumed: 1950 + (i % 5) * 30,
            targetCalories: 2000,
            rawWeightKg: Number(rawWeight.toFixed(2)),
            trendWeightKg: Number(trendWeight.toFixed(2)),
          };
        }),
        movingAverageTrend: [],
      },
      patterns: {
        timingDistribution: [
          { mealType: 'BREAKFAST', avgTime: '08:15', caloriePercentage: 23 },
          { mealType: 'LUNCH', avgTime: '13:00', caloriePercentage: 36 },
          { mealType: 'DINNER', avgTime: '19:45', caloriePercentage: 30 },
          { mealType: 'SNACK', avgTime: '21:30', caloriePercentage: 11 },
        ],
        weekdayVsWeekend: { weekdayAvg: 1960, weekendAvg: 2040 },
      },
    },
  },
};
